title: Irshad Hussain Mohammed
logo: "/profile.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data Engineering and Analytics
   <br><br>
  <a href="mailto:mirshadhussain20@gmail.com">mirshadhussain20@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/theirshadhussain/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/theirshadhussain">Github</a> 
theme: jekyll-theme-minimal
  
